package entidade;
// Generated 18/11/2019 20:56:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ActivityEvent generated by hbm2java
 */
public class ActivityEvent  implements java.io.Serializable {


     private int id;
     private Client client;
     private Event event;
     private Date date;
     private char status;
     private char sync;
     private Set checkins = new HashSet(0);

    public ActivityEvent() {
    }

	
    public ActivityEvent(int id, Client client, Event event, Date date, char status, char sync) {
        this.id = id;
        this.client = client;
        this.event = event;
        this.date = date;
        this.status = status;
        this.sync = sync;
    }
    public ActivityEvent(int id, Client client, Event event, Date date, char status, char sync, Set checkins) {
       this.id = id;
       this.client = client;
       this.event = event;
       this.date = date;
       this.status = status;
       this.sync = sync;
       this.checkins = checkins;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public char getStatus() {
        return this.status;
    }
    
    public void setStatus(char status) {
        this.status = status;
    }
    public char getSync() {
        return this.sync;
    }
    
    public void setSync(char sync) {
        this.sync = sync;
    }
    public Set getCheckins() {
        return this.checkins;
    }
    
    public void setCheckins(Set checkins) {
        this.checkins = checkins;
    }




}


