package entidade;
// Generated 18/11/2019 20:56:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int id;
     private String name;
     private String email;
     private Date birthDate;
     private char sync;
     private Set activityEvents = new HashSet(0);

    public Client() {
    }

	
    public Client(int id, String name, String email, Date birthDate, char sync) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.birthDate = birthDate;
        this.sync = sync;
    }
    public Client(int id, String name, String email, Date birthDate, char sync, Set activityEvents) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.birthDate = birthDate;
       this.sync = sync;
       this.activityEvents = activityEvents;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public char getSync() {
        return this.sync;
    }
    
    public void setSync(char sync) {
        this.sync = sync;
    }
    public Set getActivityEvents() {
        return this.activityEvents;
    }
    
    public void setActivityEvents(Set activityEvents) {
        this.activityEvents = activityEvents;
    }




}


