package entidade;
// Generated 18/11/2019 20:56:18 by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int id;
     private String users;
     private String login;
     private String password;

    public Users() {
    }

    public Users(int id, String users, String login, String password) {
       this.id = id;
       this.users = users;
       this.login = login;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsers() {
        return this.users;
    }
    
    public void setUsers(String users) {
        this.users = users;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


